### ISSUE TITLE
C libraries not built

### ISSUE THREAD

**Issue by mhardcastle** [saopicc/killMS#18]
Following the install instructions 3.2.0 appears not to build the C libraries.

```
  cd $SRC
  git clone -b v3.2.0 https://github.com/saopicc/killMS.git
  pip install $SRC/killMS
```
then later

```
Traceback (most recent call last):
  File "/usr/local/src/killMS/killMS/kMS.py", line 1353, in <module>
    driver()
  File "/usr/local/src/killMS/killMS/kMS.py", line 1335, in driver
    main(OP=OP,MSName=MSName)
  File "/usr/local/src/killMS/killMS/kMS.py", line 336, in main
    from killMS.Wirtinger.ClassWirtingerSolver import ClassWirtingerSolver
  File "/usr/local/src/killMS/killMS/Wirtinger/ClassWirtingerSolver.py", line 27, in <module>
    from killMS.Data import ClassVisServer
  File "/usr/local/src/killMS/killMS/Data/ClassVisServer.py", line 37, in <module>
    from . import ClassWeighting
  File "/usr/local/src/killMS/killMS/Data/ClassWeighting.py", line 26, in <module>
    from killMS.cbuild.Gridder import _pyGridder
ModuleNotFoundError: No module named 'killMS.cbuild'
 - 00:40:03 - ClearSHM                     | Clear shared memory
 - 00:40:03 - ClearSHM                     | Clear Semaphores
 - 00:40:03 - ClearSHM                     | Clear shared dictionaries
FAILED to run kMS.py --MSName L234026_125MHz_uv_pre-cal.ms --SolverType KAFCA --PolMode Scalar --BaseImageName PredictDI_0 --NIterKF 6 --CovQ 0.100000 --LambdaKF=0.500000 --NCPU 96 --OutSolsName DIS0 --InCol DATA --DebugPdb=0 --Weighting Natural --UVMinMax=0.100000,1000.000000 --SolsDir=SOLSDIR --SolverType CohJones --PolMode IFull --SkyModelCol DD_PREDICT --OutCol DATA_DI_CORRECTED --ApplyToDir 0 --dt 0.667693 --NChanSols 10: return value is 1
```

**Comment by bennahugo** [comment]
What version of pip are you running? Are you in a virtualenv?

Can't reproduce this my side under Python3.10 with the latest available pip
```
git clone -b v3.2.0 https://github.com/saopicc/killMS.git 
Cloning into 'killMS'...
remote: Enumerating objects: 6141, done.
remote: Counting objects: 100% (2083/2083), done.
remote: Compressing objects: 100% (571/571), done.
remote: Total 6141 (delta 1537), reused 2044 (delta 1504), pack-reused 4058
Receiving objects: 100% (6141/6141), 29.41 MiB | 5.98 MiB/s, done.
Resolving deltas: 100% (4506/4506), done.
Note: switching to '17b53f2e7db273d08f825af4e6645fcee94f8a18'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

                                                                              
bhugo@bhugo-wkslaptop ~/workspace                                  [11:29:26]
> $ virtualenv venv -p python3.10                                            
created virtual environment CPython3.10.13.final.0-64 in 914ms
  creator CPython3Posix(dest=/home/bhugo/workspace/venv, clear=False, global=False)
  seeder FromAppData(download=False, pip=latest, setuptools=latest, wheel=latest, pkg_resources=latest, via=copy, app_data_dir=/home/bhugo/.local/share/virtualenv/seed-app-data/v1.0.1.debian.1)
  activators BashActivator,CShellActivator,FishActivator,PowerShellActivator,PythonActivator,XonshActivator
                                                                              
bhugo@bhugo-wkslaptop ~/workspace                                  [11:29:41]
> $ source venv/bin/activate 

bhugo@bhugo-wkslaptop ~/workspace                                  [11:30:01]
(venv) > $ curl -sS https://bootstrap.pypa.io/get-pip.py | python3.10  
Collecting pip
  Using cached pip-24.0-py3-none-any.whl.metadata (3.6 kB)
Using cached pip-24.0-py3-none-any.whl (2.1 MB)
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 20.0.2
    Uninstalling pip-20.0.2:
      Successfully uninstalled pip-20.0.2
Successfully installed pip-24.0

(venv) > $ pip install ./killMS                                              
Processing ./killMS
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Collecting DDFacet>=0.7.0 (from DDFacet[kms-support]>=0.7.0; python_version >= "3"->killMS==3.2.0)
  Using cached ddfacet-0.8.0.0-cp310-none-any.whl

...
Successfully installed Cython-0.29.30 DDFacet-0.8.0.0 Polygon3-3.0.9.1 PyYAML-6.0.1 appdirs-1.4.4 astLib-0.11.10 astropy-5.3.4 asttokens-2.4.1 backports.shutil-get-terminal-size-1.0.0 bdsf-1.10.1 blosc2-2.6.2 click-8.1.7 cloudpickle-3.0.0 codex-africanus-0.3.5 configparser-6.0.0 contourpy-1.2.1 cycler-0.12.1 dask-2023.5.0 deap-1.4.1 decorator-5.1.1 ephem-4.1.5 exceptiongroup-1.2.1 executing-2.0.1 fonttools-4.53.0 fsspec-2024.6.0 importlib-metadata-7.1.0 ipdb-0.13.13 ipython-8.25.0 jedi-0.19.1 killMS-3.2.0 kiwisolver-1.4.5 llvmlite-0.43.0 locket-1.0.0 matplotlib-3.8.2 matplotlib-inline-0.1.7 msgpack-1.0.8 ndindex-1.8 numba-0.60.0 numexpr-2.9.0 numpy-1.22.0 packaging-24.1 pandas-2.0.3 parso-0.8.4 partd-1.4.2 pexpect-4.9.0 pillow-10.3.0 prettytable-3.9.0 prompt-toolkit-3.0.47 psutil-5.9.8 ptyprocess-0.7.0 pure-eval-0.2.2 py-cpuinfo-9.0.0 pyFFTW-0.12.0 pybind11-2.11.1 pyephem-9.99 pyerfa-2.0.1.4 pygments-2.18.0 pylru-1.2.1 pyparsing-3.1.2 python-casacore-3.5.2 python-dateutil-2.9.0.post0 pytz-2024.1 pywavelets-1.4.1 regions-0.5 ruamel.yaml-0.18.6 ruamel.yaml.clib-0.2.8 scipy-1.11.4 sharedarray-3.2.3 six-1.16.0 stack-data-0.6.3 tables-3.9.2 tomli-2.0.1 toolz-0.12.1 tqdm-4.64.0 traitlets-5.14.3 typing-extensions-4.12.2 tzdata-2024.1 wcwidth-0.2.13 zipp-3.19.2

bhugo@bhugo-wkslaptop ~/workspace                                  [11:33:21]
(venv) > $ python3                                                           
Python 3.10.13 (main, Aug 25 2023, 13:20:03) [GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from killMS.cbuild.Gridder import _pyGridder
```

**Comment by mhardcastle** [comment]
No, it's an install in our pipeline singularity image.

Pip 20.3.4 in python 3.9. I'll try upgrading, thanks.

**Comment by bennahugo** [comment]
20.3 is old. I suggest updating. I have tested it under Python 3.8 and Python 3.10. You have to keep pip up to date though

**Comment by mhardcastle** [comment]
Thanks, pip upgrade solves the problem. Could be worth updating the install instructions to mention the need for an up to date pip?

**Comment by bennahugo** [comment]
The instructions should be updated anyways --- it still mentions setup.py. I've missed updating this readme during the last release. Will look at updating it later this week.
