### ISSUE TITLE
killMS installation problem

### ISSUE THREAD

**Issue by rramij** [saopicc/killMS#8]
I have followed the following steps:
git clone https://github.com/saopicc/killMS.git
cd killMS/Predict/
make

And getting error like this:
predict.c:23:10: fatal error: arrayobject.h: No such file or directory
 #include "arrayobject.h"

When I try locating "arrayobject.h" it returns
/usr/lib64/python2.7/site-packages/numpy/core/include/numpy/arrayobject.h

I have attached a screenshot of the terminal output below.

![killMS_error](https://user-images.githubusercontent.com/25743713/73117862-e986c780-3f71-11ea-96a4-3be48a035fb7.png)

Then I added the following in the ~/.bashrc file and source it.
export PYTHONPATH=/usr/lib64/python2.7/site-packages/:${PYTHONPATH}

But no luck.

Please help me with this.

Cheers,
Ramij

**Comment by o-smirnov** [comment]
@rramij, could you try building the new Python3 branches from the private development repositories (cyriltasse/DDFacet and cyrltasse/killMS), as detailed in https://github.com/cyriltasse/killMS/issues/40#issuecomment-577673583?

The public releases on saopicc are too infrequent and out of date for your purposes -- the GMRT stuff is still on the development repos.

Your problem is definitely something to do with the build system not seeing numpy, so I'd rather try it with py3 first and diagnose problems there.

**Comment by rramij** [comment]
@o-smirnov, @cyriltasse, I only have access to cyriltasse/DDFacet but not cyrltasse/killMS.
I can only access cyriltasse/killMS_old right now.
Please add me to that repo as well.

**Comment by cyriltasse** [comment]
@rramij just invited you to the killMS repo!

**Comment by cyriltasse** [comment]
@rramij please report eventual instalation problems at

https://github.com/cyriltasse/killMS/issues/40

**Comment by bennahugo** [comment]
Note the kms build process has completely changed from what you've described. It is now pip installable along with ddfacet. Please do not muck about with environment variables :)

**Comment by candersoncsiro** [comment]
@bennahugo @o-smirnov I'm trying to install killMS on a mac and ran into the problems raised by this ticket. You say that killMS is now pip-installable...? I tried running 'pip3 install killms', but it came back saying that no versions were found. Is there a particular repo that I should be pointing to?

**Comment by bennahugo** [comment]
You need to ask @cyriltasse  to give you access to killms. It is not public (this is an ancient version). By pip installable I mean you can install the cloned repo using pip. It is not on pypi.

Note we do not officially support mac, so you may need to do this through docker.

**Comment by candersoncsiro** [comment]
OK, thanks for the info @bennahugo! 

@cyriltasse --- is it possible for me to get access to this? Happy to discuss offline if you'd prefer. My new email is canderso@nrao.edu

**Comment by cyriltasse** [comment]
Yes - no worries! I've invited you to both kMS and DDF since they work hand in hand...

**Comment by tjgalvin** [comment]
Hi @cyriltasse  - I am looking at trying this out on some data as well. Would it be possibly to get access to this? Happy to go talk over email: tim.galvin [at] csiro.au

**Comment by cyriltasse** [comment]
Sure I've invited you to both kMS/DDF repos

**Comment by candersoncsiro** [comment]
Awesome -- thanks Cyril!

---

Craig Anderson 
Jansky Fellow National Radio Astronomy Observatory
E canderso@nrao.edu T +1(575)-418-0587 
1003 Lopezville Rd, Socorro, NM 87801 
public.nrao.edu

On 16-06-2020 04:11, cyriltasse wrote:

> Sure I've invited you to both kMS/DDF repos 
> 
> --
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub [1], or unsubscribe [2]. [ { "@context": "http://schema.org", "@type": "EmailMessage", "potentialAction": { "@type": "ViewAction", "target": "https://github.com/saopicc/killMS/issues/8#issuecomment-644670444", "url": "https://github.com/saopicc/killMS/issues/8#issuecomment-644670444", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { "@type": "Organization", "name": "GitHub", "url": "https://github.com" } } ]
 

Links:
------
[1] https://github.com/saopicc/killMS/issues/8#issuecomment-644670444
[2]

**Comment by huckleclarke** [comment]
Hi @cyriltasse -- we would like to test out killMS and DDF at the Naval Research Lab for a variety of data sets. Happy to chat via e-mail tracy.clarke [at] nrl.navy.mil -- I did get DDFacet installed via stimela but then saw this ticket when I ran into killMS install issues.

**Comment by JonahDW** [comment]
Hey @cyriltasse, I'm also looking to play around with killMS on a MeerKAT dataset I've been working on. Would it be possible to get access to the repo? My email is wagenveld [at] mpifr-bonn.mpg.de

I hope its okay asking here!

**Comment by cyriltasse** [comment]
Sure I've invited you to both DDF/kMS repos...

**Comment by mauriliopannella** [comment]
Hi @cyriltasse -- I'd like to test out killMS and DDF at the UniTS cluster for the MeerKAT dataset I am working on. My e-mail is mpannella[at]units.it -- I got DDFacet installed via stimela but I am having troubles with the killMS version that seems somehow related to the numpy version.

**Comment by cyriltasse** [comment]
Hi @mauriliopannella  - could you describe a bit more the problem you're having?

**Comment by mauriliopannella** [comment]
Hi, this is the error I get when running killms (killms_301.sif). 

Traceback (most recent call last):
File "/usr/local/bin/kMS.py", line 1321, in
main(OP=OP,MSName=MSName)
File "/usr/local/bin/kMS.py", line 598, in main
PreparePredict=ClassImageSM.ClassPreparePredict(BaseImageName,VS_DDFacet,IdSharedMem,GD=GDPredict)#,IdSharedMem=IdSharedMem)
File "/usr/local/lib/python3.6/dist-packages/killMS/Predict/ClassImageSM2.py", line 104, in init
self.CreateFacetMachines()
File "/usr/local/lib/python3.6/dist-packages/DDFacet/Imager/ClassDeconvMachine.py", line 327, in CreateFacetMachines
self.FacetMachine.appendMainField(ImageName="%s.image"%self.BaseName,**MainFacetOptions)
File "/usr/local/lib/python3.6/dist-packages/DDFacet/Imager/ClassFacetMachine.py", line 283, in appendMainField
self.setFacetsLocs()
File "/usr/local/lib/python3.6/dist-packages/DDFacet/Imager/ClassFacetMachineTessel.py", line 591, in setFacetsLocs
for i in range(len(LPolygonNew))]
File "/usr/local/lib/python3.6/dist-packages/DDFacet/Imager/ClassFacetMachineTessel.py", line 591, in
for i in range(len(LPolygonNew))]
TypeError: %i format: a number is required, not numpy.ndarray


and this is how it was lunched:

singularity exec /beegfs/clustersxcosmo/oxkat/containers/killms_301.sif kMS.py --MSName 1618672936_sdp_l0_1024ch_MRC1138-262.ms --TChunk 0.5 --InCol CORRECTED_DATA -
-OutCol MODEL_DATA --BeamModel None --BaseImageName /beegfs/clustersxcosmo/oxkat/IMAGES/img_1618672936_sdp_l0_1024ch_MRC1138-262.ms_DDFpcal --NodesFile 1618672936_sd
p_l0_1024ch_MRC1138-262_facet.reg.npy --MaxFacetSize 0.25 --UVMinMax 0.15,8500.0 --FieldID 0 --DDID 0 --Weighting Natural --NCPU 40 --DoBar 0 --OutSolsName killms-co
hjones --SolverType CohJones --PolMode Scalar --dt 5 --NChanSols 8 --NIterKF 9 --CovQ 0.05  | tee /beegfs/clustersxcosmo/oxkat/LOGS/oxk_KILMS262.log
