### ISSUE TITLE
MS is not conformant

### ISSUE THREAD

**Issue by dentalfloss1** [saopicc/killMS#9]
Hi, 
I am attempting to run killMS and I see the following pasted below. I am unsure how to fix this. Attached are the log files.
[kilMS-373073-err.txt](https://github.com/saopicc/killMS/files/5417812/kilMS-373073-err.txt)
[kilMS-373073-out.txt](https://github.com/saopicc/killMS/files/5417813/kilMS-373073-out.txt)

```
- 16:24:13 - ClassMS            | [1m[91mMS is non conformant![0m[0m
Traceback (most recent call last):
  File "/usr/local/bin/kMS.py", line 1245, in <module>
    main(OP=OP,MSName=MSName)
  File "/usr/local/bin/kMS.py", line 516, in main
    GD=GD)
  File "/usr/local/lib/python2.7/dist-packages/killMS/Data/ClassVisServer.py", line 83, in __init__
    self.Init()
  File "/usr/local/lib/python2.7/dist-packages/killMS/Data/ClassVisServer.py", line 126, in Init
    MS=ClassMS.ClassMS(self.MSName,Col=self.ColName,DoReadData=False,ReadUVWDT=ReadUVWDT,GD=self.GD,**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/killMS/Data/ClassMS.py", line 64, in __init__
    self.ReadMSInfo(MSname,DoPrint=DoPrint)
  File "/usr/local/lib/python2.7/dist-packages/killMS/Data/ClassMS.py", line 681, in ReadMSInfo
    raise
```

**Comment by cyriltasse** [comment]
Hi sorry for not replying your email before - I'll send you an invite to the kMS/DDF development repo to try it with a newer version and discuss the issue...

**Comment by cyriltasse** [comment]
Hey Sarah - check this out: https://github.com/cyriltasse/killMS/issues/40

**Comment by samit97** [comment]
Hi,
I am also getting the same "MS is non-conformant" issue. Can you tell me how you solve the problem?

**Comment by bennahugo** [comment]
It is raised when not all baselines are present for all times (ie not all the data is on a regular grid). It could be caused by CASA split set to remove fully flagged rows for instance. You will need to repad your data to contain these missing rows (or resplit with the flag set to false)

**Comment by dentalfloss1** [comment]
For now, I just commented out the shape checking portion of the kMS code and it seems to run happily after that. Not sure why it would stop everything when the rest of the calibration works just fine.

**Comment by bennahugo** [comment]
@cyriltasse should comment but I think this breaks assumptions further down in the code. It is probably not safe to comment the check

**Comment by o-smirnov** [comment]
Yeah check the results very carefully. There are many ways to be non-conformant, and not all of them are necessarily fatal, so the check you commented out may well be a little over-zealous at times... but you're on shaky ground.

**Comment by dentalfloss1** [comment]
Noted. I'll compare source measurements after I finish processing.
________________________________

**Comment by cyriltasse** [comment]
Yeah - i can't remember why but there was some reason to request for this... I could dig again if it doesn't work for you @dentalfloss1
